name: Reusable workflow for JASP unit tests

on:
  workflow_call:
    inputs:
      needs_JAGS:
        description: 'Should JAGS be available?'
        required: false
        type: boolean
        default: false
      needs_igraph:
        description: '(Linux only) Should igraph be recompiled?'
        required: false
        type: boolean
        default: false
      continue_on_schedule:
        description: 'Should the workflow also be run on a schedule? By default (false), this only happens when the github.repository_owner is jasp-stats.'
        type: boolean
        default: false

jobs:
  scheduled-run-check:

    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
    - id: check
      name: Check for a scheduled run
      run: |
        if [ ${{ inputs.continue_on_schedule == 'true' || github.event_name != 'schedule' || github.repository_owner != 'jasp-stats' }} ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=error" >> $GITHUB_OUTPUT
        fi
      shell: bash

  unit-tests:

    needs: scheduled-run-check
    if: needs.scheduled-run-check.outputs.status == 'success'

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (R ${{ matrix.r }} - ${{ matrix.packages }} packages)
    continue-on-error: ${{ matrix.packages == 'latest' }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        r: [release]
        packages: [lockfile]
        include:
        - os: ubuntu-latest
          r: release
          packages: latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_LENGTH_1_CONDITION_: TRUE #deprecated from R 4.2.0
      _R_CHECK_MATRIX_DATA_: TRUE # only works from R 4.2.0 onwards

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: full

      - name: Install system dependencies on macOS specific to R devel
        if: runner.os == 'macOS' && matrix.r == 'devel'
        run: |
          # ragg                                          requires harfbuzz fribidi
          # The dependencies of the two R packages below are required for compiling from source on Ubuntu, but macOS seems fine without them
          # credentials   (dependency of usethis)         requires libgit2
          # curl          (dependency of usethis)         requires openssl

          brew install harfbuzz fribidi libgit2 openssl curl libpng
        shell: bash

      - name: Download JAGS and set JAGS_HOME on Windows
        if: runner.os == 'Windows' && inputs.needs_JAGS
        run: |
          beforeR420 <- getRversion() < "4.2.0"

          jagsUrl <- if (beforeR420) {
            'https://static.jasp-stats.org/development/JAGS-4.3.0-Windows.zip'
          } else {
            'https://static.jasp-stats.org/development/JAGS-4.3.1-Windows.zip'
          }

          destfile <- 'JAGS-Windows.zip'
          download.file(jagsUrl, destfile = destfile)
          unzip(destfile, exdir = 'JAGS')

          con <- file(description = Sys.getenv("GITHUB_ENV"), open = "a")
          on.exit(close(con))

          jagsHome <- jagsRoot <- normalizePath("JAGS", winslash = "/")
          cat("JAGS_HOME=", jagsHome, "\n", sep = "", file = con)
          cat("JAGS_ROOT=", jagsRoot, "\n", sep = "", file = con)

        working-directory: ..
        shell: Rscript {0}

      - name: Install JAGS on macOS
        if: runner.os == 'macOS' && inputs.needs_JAGS
        run: |
          # rm '/usr/local/bin/gfortran'
          brew install jags
        shell: bash

        # copied from https://github.com/r-lib/actions/blob/6b49fefb2846ed3e5e6e58366e7f7dfe01377f02/setup-r-dependencies/action.yaml#L67
      - name: Set site library path
        if: runner.os == 'Linux' && matrix.packages == 'lockfile'
        run: |
          # Set site library path
          cat("::group::Set site library path\n")
          libpak <- Sys.getenv("R_LIB_FOR_PAK")
          if (libpak != "") {
            message("R_LIB_FOR_PAK is already set to ", libpak)
          }
          if (Sys.getenv("RENV_PROJECT") != "") {
            message("renv project detected, no need to set R_LIBS_SITE")
            if (libpak == "") {
              cat(sprintf("R_LIB_FOR_PAK=%s\n", .libPaths()[1]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
              message("Setting R_LIB_FOR_PAK to ", .libPaths()[1])
            }
            q("no")
          }
          lib <- Sys.getenv("R_LIBS_SITE")
          if (lib == "") {
            lib <- file.path(dirname(.Library), "site-library")
            cat(sprintf("R_LIBS_SITE=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            message("Setting R_LIBS_SITE to ", lib)
            if (libpak == "") {
              cat(sprintf("R_LIB_FOR_PAK=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
              message("Setting R_LIB_FOR_PAK to ", lib)
            }
          } else {
            message("R_LIBS_SITE is already set to ", lib)
            if (libpak == "") {
              plib <- strsplit(lib, .Platform$path.sep)[[1]][[1]]
              cat(sprintf("R_LIB_FOR_PAK=%s\n", plib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
              message("Setting R_LIB_FOR_PAK to ", plib)
            }
          }
          if (nchar("${{ env.R_LIBS_USER && 'ok' || '' }}") == 0) {
            message("R_LIBS_USER GH env var is unset, setting now: ", Sys.getenv("R_LIBS_USER"))
            cat(sprintf("R_LIBS_USER=%s\n", Sys.getenv("R_LIBS_USER")), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          } else {
            message("R_LIBS_USER GH env var is already set: ", Sys.getenv("R_LIBS_USER"))
          }
          dir.create(Sys.getenv("R_LIBS_SITE"), recursive = TRUE, showWarnings = FALSE)
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE, showWarnings = FALSE)
          cat("::endgroup::\n")
        shell: Rscript {0}

      - name: Install pak (Unix)
        if: runner.os == 'Linux' && matrix.packages == 'lockfile'
        run: |
          # Install pak
          echo "::group::Install pak"
          if which sudo >/dev/null; then SUDO="sudo -E --preserve-env=PATH env"; else SUDO=""; fi
          $SUDO R -q -e 'dir.create(Sys.getenv("R_LIB_FOR_PAK"), recursive = TRUE, showWarnings = FALSE)'
          $SUDO R -q -e 'if (FALSE) { install.packages("pak", lib = Sys.getenv("R_LIB_FOR_PAK")) } else { install.packages("pak", lib = Sys.getenv("R_LIB_FOR_PAK"), repos = sprintf("https://r-lib.github.io/p/pak/%s/%s/%s/%s", "stable", .Platform$pkgType, R.Version()$os, R.Version()$arch)) }'
          echo "::endgroup::"
        shell: bash

      - name: Install system dependencies on linux
        if: runner.os == 'Linux' && matrix.packages == 'lockfile'
        run: |
          install.packages("renv")
          lib <- Sys.getenv("R_LIB_FOR_PAK")
          lf <- renv::lockfile_read("renv.lock")
          # TODO: this should actually use the version from the lockfile as well...
          # not sure how to do that efficiently though, we could redirect everything to
          # cran/pkg@version? that would make a ton of github api calls though
          pkgs <- vapply(lf$Packages,
               FUN = function(x) {
                 if (x$Source == "GitHub") {
                   paste0(x$RemoteUsername, "/", x$RemoteRepo)
                 } else {
                   x$Package
                 }
               },
               FUN.VALUE = character(1L)
          )
          # add jaspTools manually if missing (it requires libarchive)
          pkgs <- union(pkgs, "jasp-stats/jaspTools")
          .libPaths(lib) # make sure pak is found
          res <- pak::pkg_sysreqs(pkgs, sysreqs_platform = "ubuntu")
          cmd <- paste("sudo", res$install_scripts)
          cat(sprintf("Running cmd:\n%s\n", cmd))
          system(paste("sudo", res$install_scripts))
        shell: Rscript {0}

      - uses: r-lib/actions/setup-renv@v2
        if: matrix.packages == 'lockfile'
        with:
          cache-version: 4

      - name: Install jaspTools if missing from lockfile
        if: matrix.packages == 'lockfile'
        run: |
          if (!require("jaspTools")) renv::install("jasp-stats/jaspTools")
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: matrix.packages == 'latest'
        with:
          extra-packages: |
            any::rcmdcheck
            github::jasp-stats/jaspTools
          needs: check
          cache-version: 3

      - name: Install JAGS on Linux
        if: runner.os == 'Linux' && inputs.needs_JAGS
        run: sudo apt install jags
        shell: bash

      - name: Setup jaspTools
        run: |
          jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Run unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}
